version: "3"
networks:
  myNetwork:
    name: myNetwork
services:
  workspace:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached
    depends_on:
      - azurite
    tty: true # <- keeps container running
    networks:
      - myNetwork
# default example of a workspace spinning up docker compose
