version: '3'
networks:
  myNetwork:
    name: myNetwork
services:
  workspace:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: devcontainer.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached
      - ~/.ssh:/home/user/.ssh:ro
    depends_on:
      - azurite
    tty: true           # <- keeps container running
    networks:
      - myNetwork

# default example of a workspace spinning up docker compose