version: '3'
networks:
  myNetwork:
    name: myNetwork
services:
  azurite:
    platform: linux/arm64
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
    volumes:
      - ./azurite:/workspace
    restart: unless-stopped
    networks:
      - myNetwork