version: '3'
services:
  apicontainer:
    platform: linux/arm64
    build:
      context: .
      dockerfile: .devcontainer/apicontainer/dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - pythoncontainer

  pythoncontainer:
    platform: linux/arm64
    build:
      context: .
      dockerfile: .devcontainer/pythoncontainer/dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity